on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Install Rust
              run: rustup toolchain install stable --profile minimal --no-self-update
            - name: Cache Rust
              uses: Swatinem/rust-cache@v2
              with:
                  shared-key: "env-md"
                  key: env-md
            - name: Install mdbook
              run: cargo install mdbook
            - name: Build book
              run: mdbook build
            - name: Update toc.js
              run: ./update.sh
            # Edgeserver v0.2 Upload
            - name: Edgeserver v0.2 Upload
              uses: v3xlabs/edgeserver-upload@v0.2.1-pre.4
              with:
                site_id: s_5478c44809
                server: https://edgeserver.dev/api
                token: ${{ secrets.EDGE_TOKEN }}
                directory: book
                context: true
